# Generated by Django 5.0.6 on 2024-07-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_datapoint_insight_alter_datapoint_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
